"""Vector storage service using Qdrant.

Qdrant provides fast vector similarity search. We store embeddings alongside
metadata for hybrid search: vector similarity + structured filtering.
"""

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, PointStruct
from typing import List, Dict, Any
import uuid


# Collection name for memory embeddings
COLLECTION_NAME = "omnivia_memories"


class VectorStore:
    """Service for storing and searching vector embeddings using Qdrant.

    Stores 768-dimensional embeddings generated by the embedding service.
    Uses cosine similarity for finding semantically similar memories.

    The payload metadata includes approval_status which enables filtering
    at search time, so unverified AI memories can be excluded from results.
    """

    # Vector dimension matches nomic-embed-text-v1.5 output
    VECTOR_SIZE = 768

    def __init__(self, url: str, collection_name: str = COLLECTION_NAME):
        """Initialize the vector store connection.

        Args:
            url: Qdrant server URL (e.g., http://localhost:6333)
            collection_name: Name of the collection to use
        """
        self.url = url
        self.collection_name = collection_name
        self.client = QdrantClient(url=url)
        self._ensure_collection()

    def _ensure_collection(self):
        """Create the collection if it doesn't exist.

        Uses cosine similarity to find semantically similar vectors.
        Cosine similarity is robust to length variations in text.
        """
        collections = [c.name for c in self.client.get_collections().collections]
        if self.collection_name not in collections:
            self.client.create_collection(
                collection_name=self.collection_name,
                vectors_config={
                    "size": self.VECTOR_SIZE,
                    "distance": Distance.COSINE
                }
            )

    def upsert(self, text: str, vector: List[float], metadata: Dict[str, Any]) -> str:
        """Store a text embedding with metadata.

        Args:
            text: The original text content
            vector: 768-dimensional embedding vector
            metadata: Structured metadata including memory_id and approval_status

        Returns:
            The point ID used for storage
        """
        point_id = str(uuid.uuid4())
        self.client.upsert(
            collection_name=self.collection_name,
            points=[PointStruct(id=point_id, vector=vector, payload=metadata)]
        )
        return point_id

    def search(self, query_vector: List[float], limit: int = 5) -> List[Dict[str, Any]]:
        """Search for vectors similar to the query vector.

        Args:
            query_vector: The embedding vector to search with
            limit: Maximum number of results to return

        Returns:
            List of result dicts with id, score, and payload
        """
        results = self.client.query_points(
            collection_name=self.collection_name,
            query=query_vector,
            limit=limit
        )
        return [{"id": r.id, "score": r.score, "payload": r.payload} for r in results.points]

    def search_by_text(
        self, query_text: str, embedding_service, limit: int = 5
    ) -> List[Dict[str, Any]]:
        """Search for text similar to the query by converting text to embedding first.

        Args:
            query_text: Natural language search query
            embedding_service: Service to convert text to vector
            limit: Maximum number of results

        Returns:
            List of result dicts with id, score, and payload
        """
        query_vector = embedding_service.embed_text(query_text)
        return self.search(query_vector, limit)

    def delete(self, point_id: str) -> bool:
        """Delete a stored vector by its ID.

        Args:
            point_id: The ID of the point to delete

        Returns:
            True if deletion succeeded
        """
        try:
            self.client.delete(
                collection_name=self.collection_name,
                points_selector=[point_id]
            )
            return True
        except Exception:
            return False